### ISSUE TITLE
Variable syncing serialization is not recursive

### ISSUE THREAD

**Issue by ccmcintyre-kingsds** [Distributive-Network/Bifrost#85]
The serialization happening to sync Python and JS variables is not properly recursive, and so will cause acute issues when attempting to sync items that contain non-serializable objects.

Special handling is done by Bifrost for types such as numpy's ndarrays; if those ndarrays are hidden too deep in a larger structure being serialized, however, the special handling will not be applied, and Bifrost will simply attempt to serialize them with JSON (which will fail).

Syncing and (de)serialization needs to be made recursive, and otherwise evaluated more closely. It _may_ have functioned more robustly in practice during some past periods, but it has been a relatively neglected part of the codebase and at present time, it has become a recurring source of problems which cumulatively require some immediate attention.

Relates to #86 (Cache uses JSON without proper type checking)
Relates to #50 (Cache ignores variable reassignment between processes)

**Comment by caleb-kingsds** [comment]
Variable syncing does not correctly handle numpy arrays inside of dicts or lists.
